#!/bin/bash

echo "Executing ktlint..."

yellow='\e[33m'
red='\033[0;31m'
bold=$(tput bold)
regular=$(tput sgr0)

function successSymbol {
    	echo -e "${bold}${yellow}"
    	echo ""
    	echo ""
    	echo "              `.:////////:.`"
        echo "        ./oydmmmmmmmmmmmmmmdyo/`"
        echo "      `+hmmmmmmmmmmmmmmmmmmmmmmmmh+`"
        echo "    `smmmmmmmmmmmmmmmmmmmmmmmmmmmmmms`"
        echo "   :mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmd:"
        echo "  /mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm/"
        echo " .dmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmd."
        echo " ymmmmmmmmmmmmmmNNNNNNNNNmmmmmmmmmmmmmmmy"
        echo " mmmmmmmmmmmmNNNNNNNNNNNNNNNNmmmmmmmmmmmm"
        echo " mmmmmmmmmmdmmNNNNNNNNNNNNNNmmdmmmmmmmmmm"
        echo " mmmmmmms/::::+dNNNNNNNNNNdo::::/smmmmmmm"
        echo " mmmmmm+::::::::dNNNNNNNNd::::::::/mmmmmm"
        echo " hmmmmy:::::::::yNNNNNNNNy:::::::::ymmmmh"
        echo " ommmmd::::::::/dNNNmmNNNd/::::::::dmmmmo"
        echo " smmmmmd+:::::odNNms::smNNdo:::::+dmmmmmy"
        echo " mmmmmmmNmdddmNNNNs::::sNNNNmdddmNmmmmmmm"
        echo " mmmmmmmNNNNNNNNNm::::::mNNNNNNNNNmmmmmmm"
        echo " ommmmmmNNNNNNNNNm//+o/+mNNNNNNNNNmmmmmmo"
        echo "  .ohmmmmmNNNNNNNNmmNNNNNNNNNNNNNmmmmh+."
        echo "     `./hmmNNNNNNNNNNNNNNNNNNNmmmmh:`"
        echo "        +mmmmmdmNNNNddNNNNmdmmmmmy"
        echo "        +mmmmdhmNNNmhhmNNmmdhmmmm+"
        echo "        .ymmdhdmmmmmhhmmmmmmhdmmh."
        echo "          `.-/dmmmmmhhmmmmmd/-:`"
        echo "              `-///:..:///-"
     	echo ""
    	echo "   Ktlint successfully executed"
    	echo "${regular}"
}

function errorSymbol {
        echo -e "${bold}${red}"
    	echo ""
    	echo ""
    	echo "              `.:////////:.`"
        echo "        ./oydmmmmmmmmmmmmmmdyo/`"
        echo "      `+hmmmmmmmmmmmmmmmmmmmmmmmmh+`"
        echo "    `smmmmmmmmmmmmmmmmmmmmmmmmmmmmmms`"
        echo "   :mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmd:"
        echo "  /mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm/"
        echo " .dmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmd."
        echo " ymmmmmmmmmmmmmmNNNNNNNNNmmmmmmmmmmmmmmmy"
        echo " mmmmmmmmmmmmNNNNNNNNNNNNNNNNmmmmmmmmmmmm"
        echo " mmmmmmmmmmdmmNNNNNNNNNNNNNNmmdmmmmmmmmmm"
        echo " mmmmmmms/::::+dNNNNNNNNNNdo::::/smmmmmmm"
        echo " mmmmmm+::::::::dNNNNNNNNd::::::::/mmmmmm"
        echo " hmmmmy:::::::::yNNNNNNNNy:::::::::ymmmmh"
        echo " ommmmd::::::::/dNNNmmNNNd/::::::::dmmmmo"
        echo " smmmmmd+:::::odNNms::smNNdo:::::+dmmmmmy"
        echo " mmmmmmmNmdddmNNNNs::::sNNNNmdddmNmmmmmmm"
        echo " mmmmmmmNNNNNNNNNm::::::mNNNNNNNNNmmmmmmm"
        echo " ommmmmmNNNNNNNNNm//+o/+mNNNNNNNNNmmmmmmo"
        echo "  .ohmmmmmNNNNNNNNmmNNNNNNNNNNNNNmmmmh+."
        echo "     `./hmmNNNNNNNNNNNNNNNNNNNmmmmh:`"
        echo "        +mmmmmdmNNNNddNNNNmdmmmmmy"
        echo "        +mmmmdhmNNNmhhmNNmmdhmmmm+"
        echo "        .ymmdhdmmmmmhhmmmmmmhdmmh."
        echo "          `.-/dmmmmmhhmmmmmd/-:`"
        echo "              `-///:..:///-"
     	echo ""
    	echo "   Ktlint executed with errors, check your code"
    	echo "${regular}"
}

./gradlew ktlintCheck

RESULT=$?

if  [ $RESULT == 0 ]
then
  successSymbol
else
  errorSymbol
fi

exit $RESULT
