name: Pre Merge

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  ktlint:
    name: Check Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Run Ktlint
        run: ./gradlew ktlintCheck

  unit-test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: ktlint

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

  instrumented-test:
    name: Run Instrumented Tests
    runs-on: macos-latest
    needs: ktlint

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - run: java -cp java HelloWorldApp

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [unit-test, instrumented-test]
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    steps:
        - name: Checkout Repo
          uses: actions/checkout@v2

        - name: Cache Gradle Files
          uses: actions/setup-java@v2
          with:
            distribution: 'temurin'
            java-version: '11'
            cache: 'gradle'
        - run: ./gradlew build --no-daemon

        - name: Stop Gradle
          run: ./gradlew --stop
